### ISSUE TITLE
couldn't run

### ISSUE THREAD

**Issue by caibirdme** [cs01/gdbgui#101]
I ran `sudo pip install gdbgui --upgrade --user` to install the software,but couldn't run it anyway.
The error message looks something:
```
Traceback (most recent call last):
  File "./gdbgui", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gdbgui==0.7.9.3' distribution was not found and is required by the application
```

**Comment by cs01** [comment]
Sorry it's not working for you, let's see if we can fix it.

This is a pip/python package management problem, not necessarily a gdbgui problem, so googling for answers in general will help, but I can try to help too.

What OS are you using?
What version of pip are you using?
What is the full output of `sudo pip install gdbgui --upgrade --user`?
I think if you re-install or upgrade pip, then try to re-install gdbgui it might work for you.

Finally, the solution that always works is to use a virtual environment. See [this similar gdbgui question](https://github.com/cs01/gdbgui/issues/72) that was fixed.
