### ISSUE TITLE
Error installing on Win 10 x64 , python 3.6.3

### ISSUE THREAD

**Issue by SrMordred** [cs01/gdbgui#120]
```
C:\Users\IP-31\Desktop\gdbgui>pip install gdbgui --upgrade
Collecting gdbgui
  Using cached gdbgui-0.8.0.0.tar.gz
Collecting Flask>=0.12.2 (from gdbgui)
  Using cached Flask-0.12.2-py2.py3-none-any.whl
Collecting pygdbmi>=0.7.3.3 (from gdbgui)
  Using cached pygdbmi-0.7.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\IP-31\AppData\Local\Temp\pip-build-_h5w_yo1\pygdbmi\setup.py", line 5, in <module>
        from pygdbmi.tests import test_app
      File "C:\Users\IP-31\AppData\Local\Temp\pip-build-_h5w_yo1\pygdbmi\pygdbmi\tests\test_app.py", line 14, in <module>
        from pygdbmi.gdbcontroller import GdbController, NoGdbProcessError
      File "C:\Users\IP-31\AppData\Local\Temp\pip-build-_h5w_yo1\pygdbmi\pygdbmi\gdbcontroller.py", line 20, in <module>
        from ctypes.wintypes import HANDLE, DWORD, POINTER, BOOL
    ImportError: cannot import name 'POINTER'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\IP-31\AppData\Local\Temp\pip-build-_h5w_yo1\pygdbmi\
```

**Comment by cs01** [comment]
Thanks for filing a bug report. This is actually a known `pygdbmi` bug (which is also my project) See [issue 18 in pygdbmi](https://github.com/cs01/pygdbmi/issues/18). 

I develop only on Linux, so unfortunately I am not able to recreate or debug the issue since it's Windows-specific. If you have the time/interest, you could try to fix it yourself and submit a pull request. I think there are a lot of Windows users that would appreciate it. If you are interested I can help get you oriented with the codebase, just let me know.

**Comment by cs01** [comment]
@SrMordred pygdbmi was recently updated (https://github.com/cs01/pygdbmi/pull/23) to fix this. Try reinstalling gdbgui with `pip install gdbgui --upgrade`.
