### ISSUE TITLE
Gdb crash when: "It's been over 3 seconds. Is an inferior program loaded and running?" triggered

### ISSUE THREAD

**Issue by mitzkia** [cs01/gdbgui#128]
Hi, 

While I am using gdbgui for debugging syslog-ng I have got the following message on console "It's been over 3 seconds. Is an inferior program loaded and running?". 
I am started to investigate this, so I am started gdbgui with --debug flag, after the "reproduction" the following backtrace was in the terminal (it appears several times):
```
DEBUG: Traceback (most recent call last):
  File "/home/micek/.local/lib/python2.7/site-packages/gdbgui/backend.py", line 233, in read_and_forward_gdb_output
    response = gdb.get_gdb_response(timeout_sec=0, raise_error_on_timeout=False)
  File "/home/micek/.local/lib/python2.7/site-packages/pygdbmi/gdbcontroller.py", line 187, in get_gdb_response
    self.verify_valid_gdb_subprocess()
  File "/home/micek/.local/lib/python2.7/site-packages/pygdbmi/gdbcontroller.py", line 96, in verify_valid_gdb_subprocess
    raise NoGdbProcessError('gdb process has already finished with return code: %s' % str(self.gdb_process.poll()))
NoGdbProcessError: gdb process has already finished with return code: -11
```

Host: Ubuntu 17.10
gdb: 8.0.1
gdbgui: 0.8.0.3

**Comment by mitzkia** [comment]
Hi, 

Sorry about the wrong/misleading title, but without knowing the root cause of the crash I can not add better one. 

I can not decide what would be the good subject for this issue:
- Understand the gdb crash, why is it crashing under the gdbgui. Reproduce it with step-by-step.
And/Or
- Detect when the gdb crashes under the gdbgui. Notify the user about it, with the new message (not with the: "It's been over 3 seconds..." ). Maybe if it is possible add a possibility to re-execute the gdb from gdbgui in this case (with the same args).

**Comment by cs01** [comment]
Thanks for reporting this issue. I think gdbgui needs to be changed to do the following:

* Detect and report a missing gdb subprocess
* Automatically spawn a new gdb subprocess 
* Automatically alert the client that this occurred
* Tweak the error message to describe all possible reasons a response was not received, including that the gdb process exited unexpectedly

As to why the gdb crash occurs, it certainly appears to be a gdb bug. I recommend create a bug in their [bug database](https://sourceware.org/bugzilla/enter_bug.cgi?product=gdb&Bugzilla_restrictlogin=on&GoAheadAndLogIn=Log%20in). If you want me to create the issue, let me know. It would also help to provide the exact version of syslog-ng you're debugging, and what was going on at the time the segfault occurred so it can be reproduced by others.

**Comment by mitzkia** [comment]
Thanks, I am agreed with that (first part of the answer). 

And I have a fix reproduction steps for a gdb crash.
But at first my opinion about the crash: 
Could it be because gdb-gui stores memory addresses which was watched (clicked on the gui) during the debug session. And when I send SIGINT with "send to inferior" and my program is started to lunch again gdb-gui wanted to load previously stored memory addresses again, which are not in current state.

My reproduction is:
1, Build latest syslog-ng (v3.12) (I can help in required packages if it is needed), or install it from apt
2, Launch it with gdb-gui (example: syslog-ng -Fedv), continue untill main function
3, Set breakpoint to main_loop_run, and continue to this point
4, Start to watch local variable "+self" and click to explore its memory address
notice this in gdb console:
```
enable-pretty-printing
-var-create - * "self"
-var-list-children --all-values "var1"
-data-read-memory-bytes 0x7ffff7dd3ce0 1
-data-read-memory-bytes 0x7ffff7dd3ce1 1
-data-read-memory-bytes 0x7ffff7dd3ce2 1
-data-read-memory-bytes 0x7ffff7dd3ce3 1
-data-read-memory-bytes 0x7ffff7dd3ce4 1
-data-read-memory-bytes 0x7ffff7dd3ce5 1
-data-read-memory-bytes 0x7ffff7dd3ce6 1
-data-read-memory-bytes 0x7ffff7dd3ce7 1
-data-read-memory-bytes 0x7ffff7dd3ce8 1
-data-read-memory-bytes 0x7ffff7dd3ce9 1
-data-read-memory-bytes 0x7ffff7dd3cea 1
-data-read-memory-bytes 0x7ffff7dd3ceb 1
-data-read-memory-bytes 0x7ffff7dd3cec 1
-data-read-memory-bytes 0x7ffff7dd3ced 1
-data-read-memory-bytes 0x7ffff7dd3cee 1
-data-read-memory-bytes 0x7ffff7dd3cef 1
-data-read-memory-bytes 0x7ffff7dd3cf0 1
-data-read-memory-bytes 0x7ffff7dd3cf1 1
-data-read-memory-bytes 0x7ffff7dd3cf2 1
-data-read-memory-bytes 0x7ffff7dd3cf3 1
-data-read-memory-bytes 0x7ffff7dd3cf4 1
-data-read-memory-bytes 0x7ffff7dd3cf5 1
-data-read-memory-bytes 0x7ffff7dd3cf6 1
-data-read-memory-bytes 0x7ffff7dd3cf7 1
-data-read-memory-bytes 0x7ffff7dd3cf8 1
-data-read-memory-bytes 0x7ffff7dd3cf9 1
-data-read-memory-bytes 0x7ffff7dd3cfa 1
-data-read-memory-bytes 0x7ffff7dd3cfb 1
-data-read-memory-bytes 0x7ffff7dd3cfc 1
-data-read-memory-bytes 0x7ffff7dd3cfd 1
-data-read-memory-bytes 0x7ffff7dd3cfe 1
-data-read-memory-bytes 0x7ffff7dd3cff 1
```
5, continue running syslog-ng (gdb: c), it will say:
```
[New Thread 0x7ffff5237700 (LWP 9727)]
[2017-11-12T16:31:28.529748] syslog-ng starting up; version='3.12.1'
[Thread 0x7ffff5237700 (LWP 9727) exited]
```
6, send SIGINT with "send to inferior"
7, Allow to start running syslog-ng from the beginning (gdb: r)
At this point the terminal console will shows the backtrace:
```
DEBUG: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gdbgui/backend.py", line 233, in read_and_forward_gdb_output
    response = gdb.get_gdb_response(timeout_sec=0, raise_error_on_timeout=False)
  File "/usr/local/lib/python3.6/dist-packages/pygdbmi/gdbcontroller.py", line 187, in get_gdb_response
    self.verify_valid_gdb_subprocess()
  File "/usr/local/lib/python3.6/dist-packages/pygdbmi/gdbcontroller.py", line 96, in verify_valid_gdb_subprocess
    raise NoGdbProcessError('gdb process has already finished with return code: %s' % str(self.gdb_process.poll()))
pygdbmi.gdbcontroller.NoGdbProcessError: gdb process has already finished with return code: -11

```

**Comment by cs01** [comment]
> Could it be because gdb-gui stores memory addresses which was watched (clicked on the gui) during the debug session? And when I send SIGINT with "send to inferior" and my program is started to lunch again gdb-gui wanted to load previously stored memory addresses again, which are not in current state.

Yes that seems like a possibility. You could test this theory by repeating those actions without having the memory addresses being inspected. But in any case, gdb still should not have tried to access memory that it knows it can't.

**Comment by cs01** [comment]
Closing due to lack of activity.
