### ISSUE TITLE
TypeError exception

### ISSUE THREAD

**Issue by FlYnN91** [cs01/gdbgui#144]
Getting this exception 
![image](https://user-images.githubusercontent.com/774118/33608625-003f1670-d9bd-11e7-93a0-5038d75c6ef5.png)

- `pip freeze` output:

appdirs==1.4.3
asn1crypto==0.22.0
astroid==1.4.9
backports.functools-lru-cache==1.4
bottle==0.12.13
ccsm==0.9.13.1
chardet==3.0.4
click==6.7
colorama==0.3.9
compizconfig-python==0.9.13.1
conan==0.23.0
configparser==3.5.0
cryptography==2.1.3
distro==1.0.4
Django==1.10.1
enum-compat==0.0.2
enum34==1.1.6
eventlet==0.21.0
fasteners==0.14.1
Flask==0.12.2
Flask-Compress==1.4.0
Flask-SocketIO==2.9.2
future==0.16.0
gcovr==3.3
gdbgui==0.9.1.0
gevent==1.2.2
gitchangelog==3.0.1
greenlet==0.4.12
idna==2.5
image==1.5.4
ipaddress==1.0.17
isort==4.2.12
itsdangerous==0.24
Jinja2==2.10
keyring==10.4.0
keyrings.alt==2.2
lazy-object-proxy==1.3.1
lxml==3.6.4
Mako==1.0.6
MarkupSafe==1.0
mccabe==0.6.1
monotonic==1.3
node-semver==0.1.1
oath==1.4.1
packaging==16.8
patch==1.16
Pillow==3.3.1
pluginbase==0.5
pycairo==1.15.4
pycrypto==2.6.1
pygdbmi==0.7.4.5
Pygments==2.2.0
pygobject==3.24.1
PyJWT==1.5.0
pylint==1.6.5
pyparsing==2.2.0
pypugjs==4.2.2
pystache==0.5.4
python-engineio==2.0.1
python-socketio==1.8.3
python-vipaccess==0.3.0
pyxdg==0.25
PyYAML==3.12
qrcode==5.3
requests==2.13.0
SecretStorage==2.3.1
six==1.11.0
unity-lens-photos==1.0
Werkzeug==0.12.2
wrapt==1.10.10

- `OS`
Ubuntu 17.10
Linux ubuntu 4.13.0-17-generic #20-Ubuntu SMP Mon Nov 6 10:04:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- `gdbgui -v`
0.9.1.0

- `gdb -v (arm-none-eabi-gdb)`
> GNU gdb (GNU Tools for ARM Embedded Processors) 7.10.1.20160616-cvs
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=i686-linux-gnu --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".

- `browser`
Firefox 57.0.1 (64-bit)

**Comment by cs01** [comment]
Thanks for submitting the issue. Does gdbgui work at all, or is this raised from the start? 

It appears the [engineio](https://github.com/miguelgrinberg/python-engineio) library is [raising an exception in a way python2 doesn't like](https://github.com/miguelgrinberg/python-engineio/blob/e8e665b1737987a2b7c59cd6a96464842b864bad/engineio/socket.py#L95). This is a bug in the `engineio` library. 

If you have python3, the error will not be raised. [Issue created](https://github.com/miguelgrinberg/python-engineio/issues/58) under the project.

```
>> python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> raise
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: No active exception to reraise
```

```
>> python2
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> raise
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
>>> 
```

**Comment by cs01** [comment]
@FlYnN91 which version of Python are you using?

**Comment by cs01** [comment]
@FlYnN91 can you add steps on how to reproduce this?

**Comment by FlYnN91** [comment]
@cs01 
![image](https://user-images.githubusercontent.com/774118/33650471-0d891162-da5a-11e7-984b-6e9804c1d1eb.png)

**Comment by FlYnN91** [comment]
@cs01 I've been able to get the error again in the code base I am currently working on. My constraints are that I am using `arm-none-eabi-gdb` with `st-util` utility which connects to my ST debugger. I've only noticed the exception being thrown when I go between the break points.

**Comment by cs01** [comment]
The author of the package has updated it and thinks the issue has been resolved. He would like you to try using the latest version of the package by running the following, then running gdbgui. After you do that please post back here with results. 

    pip install https://github.com/miguelgrinberg/python-engineio/archive/master.zip

**Comment by cs01** [comment]
Closing due to lack of activity
