### ISSUE TITLE
Signal send to inferior not working for remote debugging

### ISSUE THREAD

**Issue by zhanglongqi** [cs01/gdbgui#156]
##### Describe the issue
"Signal send to inferior" is not send to remote target for remote debugging.

I am using the gdbgui for remote debugging and the target program is running on my board.
I got an error after I clicked the button `send to inferior`:
```shell
[2018-01-11 17:29:36,625] ERROR in app: Exception on /send_signal_to_pid [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/gdbgui/backend.py", line 385, in send_signal_to_pid
    os.kill(pid_int, signal_obj)
ProcessLookupError: [Errno 3] No such process
```
It seems that the backend is looking for the pid on my host machine instead of sending the signal to the remote target.

**Comment by cs01** [comment]
> It seems that the backend is looking for the pid on my host machine instead of sending the signal to the remote target.

That is correct. 

To send a signal to a process on a remote machine, gdbgui would have to run the command `kill -<signal> <pid>` *on that machine*. 

I'm not sure there is a reliable way to do this since I don't think there's always a way to run system commands remotely. What do you think?

**Comment by zhanglongqi** [comment]
Yes. You are right. Maybe we can just disable the button if it's remote debugging.

**Comment by cs01** [comment]
I think the easiest solution is to add some text when hovering over the send signal button. For example `title='send signal to pid ${pid} on the machine gdb is running on. Note: this does not work for remote processes`

**Comment by zhanglongqi** [comment]
Can it detect that it's running remotely debug and hide the button at all since there are other buttons not working in the remotely debug?

**Comment by cs01** [comment]
It can, but since the terminal is available for users to run commands, it's hard to be sure everything is in sync. I added some additional text in version 0.10.2.0, but don't want to try to detect whether it's running remotely or not because it would be error prone and not really add much value IMO.
