### ISSUE TITLE
If gdbgui is going to open a browser window, it shouldn't die on port collision

### ISSUE THREAD

**Issue by ssokolow** [cs01/gdbgui#189]
##### Describe the issue

When the user doesn't explicitly specify a port, gdbgui's default behaviour is to try port 5000 and then die if it fails to bind. This is at odds with established convention in other such tools:

Specifically, when operating in a mode which spawns its own browser window, it is convention for a "local app with a browser UI" to plan for the possibility of port collisions.. commonly, at minimum, by choosing one at random. (An example of this would be [restview](https://mg.pov.lt/restview/).)

I think it would make more sense for the current behaviour to be divided such that options such as `--remote` and `--no_browser` preserve the current failure mode while configurations which open a browser window automatically would gracefully handle a failure to bind port 5000... at the very least, by retrying with a random port if `5000` fails.

##### Steps to replicate

* Launch something else which binds to port 5000 by default
* Launch gdbgui
* Watch as you're left with an error message in the terminal and a newly-opened browser window/tab pointing at the other application

```
Opening gdbgui in browser at http://127.0.0.1:5000
exit gdbgui by pressing CTRL+C
Traceback (most recent call last):
  File "/usr/local/bin/gdbgui", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/gdbgui/backend.py", line 907, in main
    certificate=args.cert,
  File "/usr/local/lib/python2.7/dist-packages/gdbgui/backend.py", line 241, in setup_backend
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 556, in run
    self.wsgi_server.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 360, in serve_forever
    self.start()
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 304, in start
    self.init_socket()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 1450, in init_socket
    StreamServer.init_socket(self)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 127, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 138, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 229, in _tcp_listener
    sock.bind(address)
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use: ('127.0.0.1', 5000)
```

##### Describe your environment
* Operating system and version: Kubuntu Linux 14.04 LTS
* gdbgui version (`gdbgui -v`): 0.11.3.0
* gdb version (`gdb -v`): GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
* browser: Mozilla Firefox 52 ESR
* python packages (`pip freeze`):  It's quite a long list. I'll add it if you think it's relevant.

**Comment by cs01** [comment]
Cool idea.  I definitely agree that it should check if the port is in use before opening the browser.  

I will look into other tools choosing random ports when they're in use and think some more if it's something gdbgui should have.  It would be a breaking API change so I'd have to bump the major revision.

**Comment by ssokolow** [comment]
That "about 1 minute" period of time sounds like it might be related to the port being in one of the [`CLOSE_WAIT` or `TIME_WAIT` states](https://superuser.com/a/173542/48014).

To test that hypothesis, I'd start by checking whether the port shows up in `netstat -n | grep _WAIT` while the problematic behaviour is occurring.

**Comment by clesteur9** [comment]
Hello,
I still have the same issue  on "gdbgui -v =0.14.0.1"

Opening gdbgui with default browser at http://127.0.0.1:5000
View gdbgui dashboard at http://127.0.0.1:5000/dashboard
exit gdbgui by pressing CTRL+C
Traceback (most recent call last):
  File "/home/me/.local/bin/gdbgui", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gdbgui/cli.py", line 248, in main
    run_server(
  File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gdbgui/server/server.py", line 108, in run_server
    socketio.run(
  File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/flask_socketio/__init__.py", line 556, in run
    self.wsgi_server.serve_forever()
  File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gevent/baseserver.py", line 398, in serve_forever
    self.start()
  File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gevent/baseserver.py", line 336, in start
    self.init_socket()
  File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gevent/pywsgi.py", line 1482, in init_socket
    StreamServer.init_socket(self)
  File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gevent/server.py", line 180, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gevent/server.py", line 192, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gevent/server.py", line 288, in _tcp_listener
    sock.bind(address)
OSError: [Errno 98] Address already in use: ('127.0.0.1', 5000)

Does anyone have any advice to solve this problem? How to change this default adresse ?
Best regards

**Comment by ssokolow** [comment]
Run it with the `-p` option and an alternative port number.

    gdbgui -p 5432

**Comment by clesteur9** [comment]
It's works 👍 .
Thank you for the quick reply

**Comment by cmurphy208** [comment]
I am writing a tool that uses gdbgui internally. The issue is that the tool WILL be used by hundreds of developers on the same machine which obviously leads to port collisions as they can't all get port 5000.

I would ideally like to be able to use an option like '--port 0' for random port to resolve this. It is not convenient for every dev to keep trying random port numbers to find a free one manually. Also, it is not a clean solution for my script to search for the free port as this can lead to race conditions.

It is better for gdbgui to find a free port itself and then bind to it. Doesn't python have an in-built way of getting a random port?

**Comment by manikantabhagavatula** [comment]
> Hello, I still have the same issue on "gdbgui -v =0.14.0.1"
> 
> Opening gdbgui with default browser at http://127.0.0.1:5000 View gdbgui dashboard at http://127.0.0.1:5000/dashboard exit gdbgui by pressing CTRL+C Traceback (most recent call last): File "/home/me/.local/bin/gdbgui", line 8, in sys.exit(main()) File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gdbgui/cli.py", line 248, in main run_server( File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gdbgui/server/server.py", line 108, in run_server socketio.run( File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/flask_socketio/**init**.py", line 556, in run self.wsgi_server.serve_forever() File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gevent/baseserver.py", line 398, in serve_forever self.start() File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gevent/baseserver.py", line 336, in start self.init_socket() File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gevent/pywsgi.py", line 1482, in init_socket StreamServer.init_socket(self) File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gevent/server.py", line 180, in init_socket self.socket = self.get_listener(self.address, self.backlog, self.family) File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gevent/server.py", line 192, in get_listener return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family) File "/home/me/.local/pipx/venvs/gdbgui/lib/python3.8/site-packages/gevent/server.py", line 288, in _tcp_listener sock.bind(address) OSError: [Errno 98] Address already in use: ('127.0.0.1', 5000)
> 
> Does anyone have any advice to solve this problem? How to change this default adresse ? Best regards

You can use "gdbgui --host <ip-address or hostname>" option to change it's address.

**Comment by manikantabhagavatula** [comment]
> I am writing a tool that uses gdbgui internally. The issue is that the tool WILL be used by hundreds of developers on the same machine which obviously leads to port collisions as they can't all get port 5000.
> 
> I would ideally like to be able to use an option like '--port 0' for random port to resolve this. It is not convenient for every dev to keep trying random port numbers to find a free one manually. Also, it is not a clean solution for my script to search for the free port as this can lead to race conditions.
> 
> It is better for gdbgui to find a free port itself and then bind to it. Doesn't python have an in-built way of getting a random port?

Here's what I did for similar use case

```
def get_free_ports(start, end):
    free_ports = []
    for port in range(start, end+1):
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.bind(('localhost', port))
                free_ports.append(port)
        except OSError:
            pass

    return free_ports
```
