### ISSUE TITLE
`catch exec` causes segfault when following forked child process

### ISSUE THREAD

**Issue by fritzr** [cs01/gdbgui#195]
##### Description

When attempting to catch an exec() call, the application experiences a segfault.

##### Steps to replicate

Running `gdbgui --args "gcc -x c -s -"`:

```
gdbgui spawned subprocess with pid 4622 from executable gdb.
gdb process 4622 is running for this tab
GNU gdb (GDB) 7.8.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.

For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
gcc -x c++ -s -: No such file or directory.
set breakpoint pending on
Python Exception <type 'exceptions.ImportError'> No module named gdb: 
warning: 
Could not load the Python gdb module from `/data/support/share/gdb/python'.
Limited Python support is available from the _gdb module.
Suggest passing --data-directory=/path/to/gdb/data-directory.
(gdb) set follow-fork-mode child
(gdb) catch exec
Catchpoint 2 (exec)
(gdb) r
Starting program: /data/gcc-trunk/bin/gcc "-x" "c++" "-s" "-"

Breakpoint 
1, main (argc=5, argv=0x7fffffffb6f8) at /data/src/gcc-trunk/gcc/gcc-main.c:43
43    driver d (false, /* can_finalize */
(gdb) c
Continuing.
[New process 4459]
process 4459 is executing new program: /data/gcc-trunk/libexec/gcc/x86_64-pc-linux-gnu/9.0.0/cc1plus
[Switching to process 4459]

Catchpoint 
2 (exec'd /data/gcc-trunk/libexec/gcc/x86_64-pc-linux-gnu/9.0.0/cc1plus), 0x00000037cde00b30 in _start () from /lib64/ld-linux-x86-64.so.2

Program received signal 
SIGSEGV, Segmentation fault.
Cannot access memory at address 0x0

(gdb) where
Python Exception <type 'exceptions.ImportError'> No module named gdb.frames: 
#0  0x0000000000000000 in ?? ()
#1  0x0000000000000000 in ?? ()

Program received signal 
SIGSEGV, Segmentation fault.
```

Nb. as seen above 'gcc' does a vfork() followed by exec('[...]/cc1plus').
This happens consistently. Running from gdb by itself there is no segfault.

Note that I can achieve the desired effect by omitting the `catch exec` and doing simply `set follow-fork-mode child` and then `continue`, as gdbgui properly breaks in the child program's `main` function.

##### Describe your environment
* Operating system and version: CentOS 6.9 Linux 2.6.32-696.23.1.el6.centos.plus.x86_64 x86_64
* gdbgui version (`gdbgui -v`): 0.11.3.1
* gdb version (`gdb -v`): GNU gdb (GDB) 7.8.1
* browser: Firefox 52.7.0 (64-bit)
* python packages (`pip freeze`):
```
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
certifi==2017.11.5
click==6.7
decorator==4.1.2
enum34==1.1.6
Flask==0.12.4
Flask-Compress==1.4.0
Flask-SocketIO==3.0.0
funcsigs==1.0.2
gdbgui==0.11.3.1
gevent==1.3.1
greenlet==0.4.13
ipykernel==4.6.1
ipython==5.0.0
ipython-genutils==0.2.0
itsdangerous==0.24
Jinja2==2.10
jupyter-client==5.1.0
jupyter-core==4.4.0
lxml==4.2.1
manhole==1.5.0
MarkupSafe==1.0
mock==2.0.0
numpy==1.11.1
pathlib2==2.3.0
pbr==1.10.0
pdb-clone==1.10
pexpect==4.3.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
protobuf==3.0.0b2
ptyprocess==0.5.2
pygdbmi==0.8.2.0
Pygments==2.2.0
python-dateutil==2.6.1
python-engineio==2.1.1
python-socketio==1.9.0
pyzmq==16.0.3
scandir==1.6
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
tornado==4.5.2
traitlets==4.3.2
wcwidth==0.1.7
Werkzeug==0.14.1
```

**Comment by cs01** [comment]
Hmm just a guess, but try going to settings and unchecking "Attempt to flush stdout after each command is run"

**Comment by fritzr** [comment]
Wow, that actually makes it work perfectly. Good guess!

**Comment by cs01** [comment]
Since I don't have a better way to force the program being debugged to flush its buffers at this time, I am going to close this issue since it provided a workaround.
