### ISSUE TITLE
Server crashes when sending signal to gdb or inferior using GUI

### ISSUE THREAD

**Issue by fritzr** [cs01/gdbgui#196]
##### Description

Anytime I use the GUI button to send a signal to either gdb or an inferior, the server experiences a Python exception and no longer responds to some commands.

##### Steps to replicate

Start `gdbgui` and click `send to gdb`. This also reproduces for me when I am attached to an inferior, and I click the `send to inferior` button.

In the server terminal I see:
```
$ gdbgui
Opening gdbgui in browser at http://127.0.0.1:5000
exit gdbgui by pressing CTRL+C
[2018-05-18 18:45:39,742] ERROR in app: Exception on /send_signal_to_pid [POST]
Traceback (most recent call last):
  File "/data/support/lib/python2.7/site-packages/Flask-0.12.4-py2.7.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/support/lib/python2.7/site-packages/Flask-0.12.4-py2.7.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/support/lib/python2.7/site-packages/Flask-0.12.4-py2.7.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/support/lib/python2.7/site-packages/Flask-0.12.4-py2.7.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/support/lib/python2.7/site-packages/Flask-0.12.4-py2.7.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/support/lib/python2.7/site-packages/gdbgui-0.11.3.1-py2.7.egg/gdbgui/backend.py", line 575, in send_signal_to_pid
    % (signal_name, signal_obj.value, pid_str)
AttributeError: 'int' object has no attribute 'value'
```

The web console reports:
```
INTERNAL SERVER ERROR (500 error)
```

Some commands continue to function, though sometimes after a long response time. Occasionally the web console says:
```
No gdb response received after 10 seconds. This usually indicates an error.
Possible reasons include:
1) an inferior program was not loaded; 2) gdb or the inferior process need to be interrupted with the SIGNINT signal; 3) gdb has exited unexpectedly; 4) an unexpected error occurred
If an operation that takes longer than 10 seconds was run, this message can be ignored.
```

##### Environment
* Operating system and version: Linux 2.6.32-696.23.1.el6.centos.plus.x86_64 x86_64 GNU/Linux
* gdbgui version (`gdbgui -v`): 0.11.3.1
* gdb version (`gdb -v`): GNU gdb (GDB) 7.8.1
* browser: Firefox 52.7.0
* python packages (`pip freeze`):
```
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
certifi==2017.11.5
click==6.7
decorator==4.1.2
enum34==1.1.6
Flask==0.12.4
Flask-Compress==1.4.0
Flask-SocketIO==3.0.0
funcsigs==1.0.2
gdbgui==0.11.3.1
gevent==1.3.1
greenlet==0.4.13
ipykernel==4.6.1
ipython==5.0.0
ipython-genutils==0.2.0
itsdangerous==0.24
Jinja2==2.10
jupyter-client==5.1.0
jupyter-core==4.4.0
lxml==4.2.1
manhole==1.5.0
MarkupSafe==1.0
mock==2.0.0
numpy==1.11.1
pathlib2==2.3.0
pbr==1.10.0
pdb-clone==1.10
pexpect==4.3.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
protobuf==3.0.0b2
ptyprocess==0.5.2
pygdbmi==0.8.2.0
Pygments==2.2.0
python-dateutil==2.6.1
python-engineio==2.1.1
python-socketio==1.9.0
pyzmq==16.0.3
scandir==1.6
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
tornado==4.5.2
traitlets==4.3.2
wcwidth==0.1.7
Werkzeug==0.14.1
```

**Comment by cs01** [comment]
I fixed one very similar to this before. I think I may have fixed it in one version of python and broke it in another.  Thanks for filing these issues, it will help make the tool better.  Hopefully you are getting some use out of gdbgui and not just hitting bug after bug.

**Comment by fritzr** [comment]
Yes it is still incredibly useful! Everything has been something I can work around easily enough. I’ve come from spamming the ‘list’ command in gdb every few seconds so this is a *little* better 😁
