### ISSUE TITLE
Errors when the project path has no ASCII characters

### ISSUE THREAD

**Issue by Martin1887** [cs01/gdbgui#207]
**Describe the bug**
When the project path contains no ASCII characters some bugs appear:

- The file chooser shows numbers instead that characters. For instance, `Mart303255n` instead `Martín`. When a file is chosen, it cannot be found and the no ASCII character has to be manually written (sometimes it is not found anyway).
- Inserting breakpoints causes the following error and there are no manner of inserting a breakpoint: 

```
Error occurred on server when running gdb command: Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/gdbgui/backend.py", line 359, in run_gdb_command controller.write(cmd, read_response=False) File "/usr/lib/python2.7/site-packages/pygdbmi/gdbcontroller.py", line 204, in write self.gdb_process.stdin.write(mi_cmd_to_write_nl.encode()) UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 31: ordinal not in range(128)
```

**To Reproduce**

1. `gdbgui target/debug/program_name` from the project path in a project with no ASCII characters in the path.
2. Open a src file.
3. Click in a line to insert a breakpoint or insert a breakpoint from the console.

**Expected behavior**
No errors and breakpoint inserted.

**Please complete the following information:**
* OS: Fedora 28
* gdbgui version (`gdbgui -v`): 0.12.0.0
* gdb version (`gdb -v`): 0.1-15.fc28
* browser [e.g. chrome, safari]: Firefox 60.0.1
* python packages (`pip freeze`):
```
asn1crypto==0.24.0
backports.ssl-match-hostname==3.5.0.1
bcrypt==3.1.4
Beaker==1.5.4
beautifulsoup4==4.6.0
cffi==1.11.5
chardet==3.0.4
click==6.7
cryptography==2.2.1
cssselect==0.9.2
decorator==4.2.1
ecdsa==0.13
enum34==1.1.6
f.lux-indicator-applet==1.1.8
Flask==0.12.4
Flask-Compress==1.4.0
Flask-SocketIO==2.9.6
galternatives==0.9
gcalcli==3.4.0
gdbgui==0.12.0.0
gevent==1.3.2.post0
google-api-python-client==1.6.5
greenlet==0.4.13
gssapi==1.5.0
html5lib==0.999999999
httplib2==0.10.3
idna==2.5
ipaddr==2.1.10
ipaddress==1.0.18
IPy==0.81
itsdangerous==0.24
Jinja2==2.10
libvirt-python==4.1.0
lxml==4.1.1
Mako==1.0.6.dev0
MarkupSafe==1.0
mplleaflet==0.0.5
nose==1.3.7
numpy==1.14.3
oauth2client==1.4.12
olefile==0.45.1
paramiko==2.4.1
Paste==2.0.3
pexpect==4.3.1
Pillow==5.1.1
ply==3.9
polib==1.0.7
ptyprocess==0.5.2
pyasn1==0.3.7
pyasn1-modules==0.2.1
pycairo==1.16.3
pycparser==2.14
pycrypto==2.6.1
pycryptopp==0.6.0.1206569328141510525648634803928199668821045408958
pygdbmi==0.8.3.0
Pygments==2.2.0
pygobject==3.28.2
pyinotify==0.9.6
pymongo==3.6.1
PyNaCl==1.2.0
pyOpenSSL==17.3.0
PyPAM==0.5.0
PySocks==1.6.8
python-dateutil==2.6.1
python-engineio==2.1.1
python-gflags==3.1.2
python-socketio==1.9.0
pyxdg==0.25
PyYAML==3.12
reportlab==3.4.0
requests==2.18.4
rsa==3.4.2
scour==0.35
sepolicy==1.1
setools==4.1.1
setproctitle==1.1.10
six==1.11.0
Tempita==0.5.1
uniconvertor==2.0
uritemplate==3.0.0
urllib3==1.22
vboxapi==1.0
webencodings==0.5.1
Werkzeug==0.14.1
xi-plugin==0.1
```

**Comment by cs01** [comment]
Thanks for filing. I reproduced and am working on it.
