### ISSUE TITLE
TypeError: string argument expected, got 'NoneType' while installing gdbgui by pip

### ISSUE THREAD

**Issue by iosmanthus** [cs01/gdbgui#231]
**Describe the bug**
when I try to install `gdbgui` in another machine by `pip`, `pip` raises an exception:
```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/usr/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3.7/site-packages/pip/_internal/resolve.py", line 261, in _resolve_one
    check_dist_requires_python(dist)
  File "/usr/lib/python3.7/site-packages/pip/_internal/utils/packaging.py", line 46, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "/usr/lib/python3.7/email/feedparser.py", line 175, in feed
    self._input.push(data)
  File "/usr/lib/python3.7/email/feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'
```
**Screenshots**
![screenshot from 2018-09-21 20-23-29](https://user-images.githubusercontent.com/16307070/45880963-3f76b880-bddc-11e8-8916-d67c465fd037.png)

**Please complete the following information:**
* OS: 
ArchLinux
* gdb version (`gdb -v`): 
GNU gdb (GDB) 8.2
* browser [e.g. chrome, safari]:
chrome
* python packages (`pip freeze`):
```
appdirs==1.4.3
backcall==0.1.0
beautifulsoup4==4.6.3
Brlapi==0.6.7
btrfsutil==1.0.0
CacheControl==0.12.5
chardet==3.0.4
click==6.7
colorama==0.3.9
cycler==0.10.0
decorator==4.3.0
distlib==0.2.7
distro==1.3.0
et-xmlfile==1.0.1
Flask==0.12.4
Flask-Compress==1.4.0
Flask-SocketIO==2.9.6
gevent==1.3.6
gmpy2==2.1.0a2
greenlet==0.4.15
html5lib==1.0.1
idna==2.7
ipython==6.5.0
ipython-genutils==0.1.0
itsdangerous==0.24
jdcal==1.4
jedi==0.12.1
Jinja2==2.10
kiwisolver==1.0.1
lensfun==0.3.2
lockfile==0.12.2
louis==3.7.0
lxml==4.2.5
MarkupSafe==1.0
matplotlib==2.2.3
msgpack==0.5.6
openpyxl==2.5.7
packaging==17.1
parso==0.3.1
pexpect==4.6.0
pickleshare==0.7.4
progress==1.4
prompt-toolkit==1.0.15
psutil==5.4.7
ptyprocess==0.6.0
pycairo==1.17.0
pygdbmi==0.8.3.0
Pygments==2.2.0
PyGObject==3.30.1
pyparsing==2.2.1
pyte==0.8.0
python-dateutil==2.7.3
python-engineio==2.2.0
python-socketio==2.0.0
pytoml==0.1.16
pytz==2018.5
pyxdg==0.26
requests==2.19.1
retrying==1.3.3
scipy==1.1.0
shadowsocks==2.9.1
simplegeneric==0.8.1
six==1.11.0
team==1.0
thefuck==3.27
traitlets==4.3.2
urllib3==1.23
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
ydcv==0.5

```

**Comment by cs01** [comment]
Thanks for reporting. I'll try to reproduce and fix the issue. Looks like it might have something to do with Python 3.7.

What was the command you ran? `pip install gdbgui`? You mentioned you tried to install "in another machine", was there anything unique or unusual about the setup?
