### ISSUE TITLE
gdbgui pygdbmi gbi mi server commands

### ISSUE THREAD

**Issue by navinp0304** [cs01/gdbgui#363]
When i run **gdbgui** , i click on certain frame gdb crashes with readline no handler. I'm **not able to reproduce** the error in gdb commandline. I want to **log all the mi commands sent and response**  logged. I want to **replay** the command and look for **response** to check whether it is a bug .

- Can you help me with this ?

**Comment by cs01** [comment]
https://www.gdbgui.com/faq/ explains how to do this

**Comment by navinp0304** [comment]
When i run in debug mode i get only this output. I wanted to trace the mi commands sent and response code.I think this may need help from pygdbmi.


```
navin@mint-Aspire:~/gdbgui/readline$ gdbgui --debug
View gdbgui at http://127.0.0.1:5000
View gdbgui dashboard at http://127.0.0.1:5000/dashboard
exit gdbgui by pressing CTRL+C
(2020-11-14 18:47:41,712)  * Restarting with stat
View gdbgui at http://127.0.0.1:5000
View gdbgui dashboard at http://127.0.0.1:5000/dashboard
exit gdbgui by pressing CTRL+C
(2020-11-14 18:47:43,466)  * Debugger is active!
(2020-11-14 18:47:43,474)  * Debugger PIN: 628-690-423
(222636) wsgi starting up on http://127.0.0.1:5000
(222636) accepted ('127.0.0.1', 59734)
(222636) accepted ('127.0.0.1', 59736)
127.0.0.1 - - [14/Nov/2020 18:47:46] "GET / HTTP/1.1" 200 1270 0.038450
127.0.0.1 - - [14/Nov/2020 18:47:47] "GET /socket.io/?csrf_token=bfb07fa58318a40d154956f09318e0c994f79532&gdbpid=0&gdb_command=gdb&EIO=3&transport=polling&t=NN6vvOo HTTP/1.1" 200 371 0.003341
127.0.0.1 - - [14/Nov/2020 18:47:48] "GET /socket.io/?csrf_token=bfb07fa58318a40d154956f09318e0c994f79532&gdbpid=0&gdb_command=gdb&EIO=3&transport=polling&t=NN6vvYk&sid=8cc758839cf749ca9566e0d5b3c2c8c3 HTTP/1.1" 200 340 0.002683
(222636) accepted ('127.0.0.1', 59738)
127.0.0.1 - - [14/Nov/2020 18:47:48] "POST /socket.io/?csrf_token=bfb07fa58318a40d154956f09318e0c994f79532&gdbpid=0&gdb_command=gdb&EIO=3&transport=polling&t=NN6vvYC&sid=8cc758839cf749ca9566e0d5b3c2c8c3 HTTP/1.1" 200 219 0.048913
127.0.0.1 - - [14/Nov/2020 18:47:48] "GET /socket.io/?csrf_token=bfb07fa58318a40d154956f09318e0c994f79532&gdbpid=0&gdb_command=gdb&EIO=3&transport=polling&t=NN6vvi0&sid=8cc758839cf749ca9566e0d5b3c2c8c3 HTTP/1.1" 200 183 0.001007
127.0.0.1 - - [14/Nov/2020 18:47:48] "GET /static/favicon.ico HTTP/1.1" 200 14283 0.045225
127.0.0.1 - - [14/Nov/2020 18:47:51] "GET /get_last_modified_unix_sec?path=~%2Felfutils%2Felfutils%2Fsrc%2Felflint&_=1605359866940 HTTP/1.1" 400 245 0.021307
127.0.0.1 - - [14/Nov/2020 18:47:53] "GET /read_file?start_line=1&end_line=501&path=%2Fhome%2Fnavin%2Felfutils%2Felfutils%2Fsrc%2Felflint.c&highlight=true&_=1605359866941 HTTP/1.1" 200 7709 2.475198
127.0.0.1 - - [14/Nov/2020 18:48:12] "GET /read_file?start_line=1020&end_line=1520&path=%2Fhome%2Fnavin%2Felfutils%2Felfutils%2Fsrc%2Felflint.c&highlight=true&_=1605359866942 HTTP/1.1" 200 7131 0.142911
(2020-11-14 18:48:31,531) [Errno 5] Input/output error
Traceback (most recent call last):
  File "/home/navin/.local/lib/python3.8/site-packages/gdbgui/server/app.py", line 274, in check_and_forward_pty_output
    response = debug_session.pty_for_gdb.read()
  File "/home/navin/.local/lib/python3.8/site-packages/gdbgui/server/ptylib.py", line 77, in read
    response = os.read(self.stdout, self.max_read_bytes).decode()
OSError: [Errno 5] Input/output error
127.0.0.1 - - [14/Nov/2020 18:48:31] "GET /socket.io/?csrf_token=bfb07fa58318a40d154956f09318e0c994f79532&gdbpid=0&gdb_command=gdb&EIO=3&transport=websocket&sid=8cc758839cf749ca9566e0d5b3c2c8c3 HTTP/1.1" 200 0 43.522686
```

**Comment by cs01** [comment]
The mi output is displayed in the browser window at the bottom of the right pane
