### ISSUE TITLE
gdbgui runtime error when resizing the bottom panes

### ISSUE THREAD

**Issue by navinp0304** [cs01/gdbgui#364]
I was trying to resize the gdb window up and tried to left when i saw this error. In app.py i changed it to copy().items since the iterator is changed at runtime. It didn't crash after that.
 Btw can we change the size of gdb command window and increase width ?
`
 for debug_session, client_ids in manager.debug_session_to_client_ids.copy().items():
`

```
Traceback (most recent call last):

  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/home/navin/.local/lib/python3.8/site-packages/gdbgui/server/app.py", line 231, in read_and_forward_gdb_and_pty_output
    for debug_session, client_ids in manager.debug_session_to_client_ids.items():
RuntimeError: dictionary changed size during iteration
2020-11-14T12:19:39Z <Thread at 0x7fbac8c87ae0: read_and_forward_gdb_and_pty_output> failed with RuntimeError
```

**Comment by pecastro** [comment]
Seeing a similar thing to the above but in my case when trying to debug a rust program whilst I was figuring out how to load the sources after the "File not found: main" event.

```
Warning: authentication is recommended when serving on a publicly accessible IP address. See gdbgui --help.
View gdbgui at http://172.17.0.2:5000
View gdbgui dashboard at http://172.17.0.2:5000/dashboard
exit gdbgui by pressing CTRL+C
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.8/site-packages/gdbgui/server/app.py", line 231, in read_and_forward_gdb_and_pty_output
    for debug_session, client_ids in manager.debug_session_to_client_ids.items():
RuntimeError: dictionary changed size during iteration
2021-02-24T22:40:24Z <Thread at 0x7f459273fbf0: read_and_forward_gdb_and_pty_output> failed with RuntimeError

(2021-02-24 22:40:24,873) %s is not connected to namespace %s
(2021-02-24 22:40:24,874) %s is not connected to namespace %s
(2021-02-24 22:40:24,874) %s is not connected to namespace %s
(2021-02-24 22:40:24,874) %s is not connected to namespace %s
(2021-02-24 22:40:24,874) %s is not connected to namespace %s
```

**Comment by cs01** [comment]
Thanks for reporting. Unfortunately I don’t currently have time to look into this right now, but it should be fixable with some slight refactoring.
