### ISSUE TITLE
When using gdbgui in ubuntu16, python3.5, syntax error happened

### ISSUE THREAD

**Issue by ArkcS** [cs01/gdbgui#410]
When im using gdbgui in ubuntu16 with python3.5, the gdbgui version is 0.13.2.0, error happened

> Traceback (most recent call last):
>   File "/root/.virtualenvs/venvgdbgui/bin/gdbgui", line 5, in <module>
>     from gdbgui.backend import main
>   File "/root/.virtualenvs/venvgdbgui/lib/python3.5/site-packages/gdbgui/backend.py", line 38, in <module>
>     from gdbgui.statemanager import StateManager  # noqa
>   File "/root/.virtualenvs/venvgdbgui/lib/python3.5/site-packages/gdbgui/statemanager.py", line 3, in <module>
>     from pygdbmi.gdbcontroller import GdbController
>   File "/root/.virtualenvs/venvgdbgui/lib/python3.5/site-packages/pygdbmi/gdbcontroller.py", line 82
>     logger.debug(f'Launching gdb: {" ".join(self.command)}')
>                                                           ^
> SyntaxError: invalid syntax

**Comment by misutoneko** [comment]
Upgrade, if you can...yeah I know, that's what they always say :D
I suspect your error message is a result of the code being run by python2 and not python3 (Ubuntu16 has both).
You could try changing the default python to python3 and see if that helps.

**Comment by cgringmuth** [comment]
I think the issue here is that format strings `f""` are supported starting from python 3.6. I have the same issue and I cannot upgrade the ubuntu version. I think that python 3.5 is the latest version for this ubuntu.
