### ISSUE TITLE
server() got an unexpected keyword argument 'ssl_context'

### ISSUE THREAD

**Issue by manikantabhagavatula** [cs01/gdbgui#472]
**Describe the bug**
TypeError: server() got an unexpected keyword argument 'ssl_context'

**To Reproduce**
1. Install gdbgui via pip following this documentation, https://www.gdbgui.com/installation/
2. Generate key and cert files as described in the help (gdbgui -h)
3. Once the key and cert files are ready, run gdbgui with this arguments "--host <host.key> --cert <host.cert>"

**Expected behavior**
Open gdbgui in a browser window with https in the url.

Opening gdbgui with default browser at https://127.0.0.1:5000
View gdbgui dashboard at https://127.0.0.1:5000/dashboard

**Python Traceback**
Traceback (most recent call last):
  File "../myvenv/bin/gdbgui", line 8, in <module>
    sys.exit(main())
  File "../myvenv/lib/python3.6/site-packages/gdbgui/cli.py", line 258, in main
    certificate=args.cert,
  File "../myvenv/lib/python3.6/site-packages/gdbgui/server/server.py", line 100, in run_server
    **kwargs,
  File "../myvenv/lib/python3.6/site-packages/flask_socketio/__init__.py", line 630, in run
    run_server()
  File "../myvenv/lib/python3.6/site-packages/flask_socketio/__init__.py", line 625, in run_server
    log_output=log_output, **kwargs)
TypeError: server() got an unexpected keyword argument 'ssl_context'

**Please complete the following information:**
* OS: rhel8
* gdbgui version (`gdbgui -v`): 0.15.1.0
* gdb version (`gdb -v`): 13.1.0
* browser [e.g. chrome, safari]: Chrome
* python packages (`pip freeze`): Long list. Can post if needed

**Comment by SatGarcia** [comment]
I'm running into the same issue with gdbgui 0.15.2 on Ubuntu.

It seems like newer versions of eventlet.wsgi.server (used in the flask_socketio package) don't want an ssl_context as a kwarg, and instead want you to pass in certfile and keyfile as kwargs to set up an SSL connection.
