### ISSUE TITLE
Exception on /read_file [GET]

### ISSUE THREAD

**Issue by kvark** [cs01/gdbgui#56]
The GUI displays ""failed to fetch file at path (some_file).cpp"", where the path exists (I can do ls -l some_file.cpp and get the output).

Full console log:
```
[2017-03-27 12:39:55,389] ERROR in app: Exception on /read_file [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/gdbgui/backend.py", line 312, in read_file
    highlight = json.loads(request.args.get('highlight'))
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by cs01** [comment]
Interesting, sorry you are encountering this. I have not seen this before.

The error you pasted is not saying the file does not exist; it is saying it can't decode a JSON object from the "highlight" parameter that should have been sent by the client.

Answers to these questions will help me to debug the issue:

1. Have you upgraded gdbgui recently, and did this start occurring after the upgrade? The backend is expecting the `highlight` parameter, which only newer client code sends (these two should always be in sync, I'm not sure how they'd get out of sync).  
1. When did it start happening? Does this always occur everytime gdbgui tries to open a file? 
1. If not, are you doing anything differently when the error occurs?

**Comment by kvark** [comment]
Thanks for the prompt response!

  1. I just installed it via "sudo pip install gdbgui --upgrade". My system is: "4.9.7-201.fc25.x86_64 #1 SMP"
  2. I simply start `gdbgui` with my app and get this instantly and consistently.

**Comment by cs01** [comment]
I can't replicate the issue, but I can allow it to fail more gracefully so you can still get your source code.

**Comment by cs01** [comment]
Another question: Are you using any character encoding overrides? Something other than utf-8?

**Comment by kvark** [comment]
> Are you using any character encoding overrides? 

Nope

>Would you be open to testing a fix branch?

Thanks, that seems to work for me!

**Comment by cs01** [comment]
Nice, I'll merge to master and update the pypi version.
