### ISSUE TITLE
Source code display fails

### ISSUE THREAD

**Issue by guttinasrinivas** [cs01/gdbgui#63]
**Exception stack:**
```
[2017-04-23 13:11:45,058] ERROR in app: Exception on /read_file [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/gdbgui/backend.py", line 311, in read_file
    highlight = json.loads(request.args.get('highlight', 'true'))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
**OS**: ```Ubuntu 16.04.2 LTS```
**Kernel**: ```Linux 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux```
**GDB Version Info**:
```
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
This GDB was configured as "x86_64-linux-gnu".
```
**Browser**: ```Google Chrome Version 58.0.3029.81 (64-bit)```

**Comment by cs01** [comment]
Apologies for the inconvenience. Thanks for filing the bug.

It looks like your browser is using a cached version of gdbgui. I suspect you upgraded gdbgui from an older version, and chrome didn't refetch the main frontend file `gdbgui.js`.

I am going to add some functionality that ensures this doesn't happen. In the mean time, follow [these instructions](http://stackoverflow.com/a/8392547/2893090) to clear the cache, then refresh. It should work after that. Let me know if this helps.

**Comment by guttinasrinivas** [comment]
Oh, this was a fresh install. I just came across this tool. Incredible job, BTW.

Thanks for the fix.

**Comment by cs01** [comment]
@guttinasrinivas thanks, much appreciated
