### ISSUE TITLE
Automatically crashes after 10 seconds

### ISSUE THREAD

**Issue by noscript** [cs01/gdbgui#76]
Simply running gdbgui and waiting:
```
$ gdbgui './mycmd --arg1 --arg2'
Opening gdbgui in browser (http://127.0.0.1:5000)


** view app at http://127.0.0.1:5000 **


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 935, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 908, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 268, in handle_request
    self.disconnect(sid)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 202, in disconnect
    self._get_socket(sid).close()
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 411, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
Thu Jun 15 11:51:06 2017 {'REMOTE_PORT': '50580', 'HTTP_HOST': '127.0.0.1:5000', 'REMOTE_ADDR': '127.0.0.1', (hidden keys: 23)} failed with KeyError

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 935, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 908, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 42, in __call__
    start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 268, in handle_request
    self.disconnect(sid)
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 202, in disconnect
    self._get_socket(sid).close()
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 411, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
Thu Jun 15 11:51:06 2017 {'REMOTE_PORT': '50584', 'HTTP_HOST': '127.0.0.1:5000', 'REMOTE_ADDR': '127.0.0.1', (hidden keys: 23)} failed with KeyError
```

That apparently happens when I switch from Firefox to Chrome, due to #75.

**Comment by cs01** [comment]
According to https://github.com/miguelgrinberg/Flask-SocketIO/issues/179, it's due to a delayed client SocketIO response.
> The fix is to increase the `pingTimeout` in the `SocketIO` constructor. 

However, the default timeout is 60 seconds, which seems a little suspect since there is no way the client isn't communicating for 60 full seconds.

> That apparently happens when I switch from Firefox to Chrome, due to #75.

It is possible the extra time Chrome takes to render the console results in the timeout error.

I'll try increasing the timeout and see if it helps.

**Comment by cs01** [comment]
@noscript I made a branch called `update-socketio` where I updated the socketio client version from 1.3.5 to 2.0.3 and the timeout duration from default  (20 seconds I think) to 5 minutes.

Can you try using this branch and let me know if it helps?

**Comment by cs01** [comment]
@noscript this has been merged into master, hopefully it was helpful. Feel free to close if appropriate.

**Comment by cs01** [comment]
@noscript any updates with this? Let me know if you're still seeing problems here, otherwise feel free to close the issue.

**Comment by noscript** [comment]
I did not find `update-socketio` branch, but in `master ` it seems not to lose connection anymore. Thanks!
